version: '2'
services:
  receipt_service:
    container_name: receipt_service
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
    build: 
      context: .
    networks:
      - receipt_service
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    ports:
      - "5000:5000" 
    restart: on-failure
    tty: true  
networks:
  receipt_service:
volumes:
  pgdata:    