### add receipt
POST http://localhost:5000/api/receipt
content-type: application/json

{
    "category" : "Transport",
    "title"  :  "test 3",
    "cost"    : 100
}


### get receipt via id
get http://localhost:5000/api/receipt/1
content-type: application/json



### get all receipt
POST http://localhost:5000/api/receipt/list
content-type: application/json


### get reports file 
get http://localhost:5000/api/receipt/get/reports
content-type: application/octet-stream


